Data cleaning
NFDI4BIOIMAGE/training pull request #127
Opened 2024-07-19 09:44 UTC by SeverusYixin

This script normalizes variables in YAML files, particularly focusing on the following:

License Names:

It fetches the SPDX license list from the SPDX website and uses it to standardize license names to their canonical SPDX IDs.

Author Names:

It handles different formats of author names, including:
"Last, First" format.
"First Last" format.
Complex structures like "Last, First, Last, First".
Ensures consistency in author name representation across the data.

Tags:

Normalizes tags to a consistent format, ensuring they are uniformly capitalized and stripped of extraneous spaces.

Types:

Ensures all types are represented as lists and are uniformly capitalized and stripped of extraneous space.

Hi @haesleinhuepf, would you mind to review this PR when you have a moment. Thanks a lot :)

This PR closes #99

2024-07-19 10:05 UTC, haesleinhuepf commented
Hi @SeverusYixin ,

I'm happy to review this. Would you mind writing some sentences what these changes are doing? What features did you implement?

Thanks!

Best,
Robert

2024-07-19 10:09 UTC, SeverusYixin commented
> Hi @SeverusYixin ,
> 
> I'm happy to review this. Would you mind writing some sentences what these changes are doing? What features did you implement?
> 
> Thanks!
> 
> Best, Robert

Let me check it

2024-07-19 11:01 UTC, haesleinhuepf requested changes
Hi @SeverusYixin ,

thanks for sending this PR! You find some detailed comments below. Furthemore, I was hoping that this code would be execute as part of the [github workflows](https://github.com/NFDI4BIOIMAGE/training/tree/main/.github/workflows). Yould you please enter it there and make sure that the scripts are executed when a pull-request is sent (test.yml) or when the book is deployed (book.yml).

Please change those things and tag me afterwards, I'm happy to take another look.

Thanks!

Best,
Robert

2024-07-19 11:14 UTC, SeverusYixin commented on scripts/data_normalizer.py
> +def normalize_author_list(authors):
It should be the code that I had blocked out earlier that I inadvertently unblocked, I've removed and updated it

2024-07-19 11:36 UTC, SeverusYixin commented on scripts/data_normalizer.py
> +def normalize_author_list(authors):
the first one, I have update it

2024-07-19 12:20 UTC, SeverusYixin commented on scripts/data_normalizer.py
> +def create_mapping(items):
Do you want to do this next time or do you want me to change the current code, I'm still working on it

2024-07-19 12:21 UTC, SeverusYixin commented
@haesleinhuepf Would you mind to review it again

2024-07-19 14:29 UTC, haesleinhuepf commented on .github/workflows/book.yml
> +    # Run data normalizer script after builded the book
Shouldn't the data normalizer be executed before building the book?

2024-07-19 14:37 UTC, haesleinhuepf commented on scripts/data_normalizer.py
> +def create_mapping(items):
I would love to improve code quality before merging this. Otherwise we will forget to do this.

2024-07-19 14:38 UTC, haesleinhuepf commented
> Would you mind to review it again

Please finish the code quality improvement (docstrings) first.

And have a great weekend btw!

2024-07-19 14:46 UTC, SeverusYixin commented on scripts/data_normalizer.py
> +def create_mapping(items):
Got it

2024-07-19 14:53 UTC, SeverusYixin commented on .github/workflows/book.yml
> +    # Run data normalizer script after builded the book
right

2024-07-19 14:54 UTC, SeverusYixin commented
> > Would you mind to review it again
> 
> Please finish the code quality improvement (docstrings) first.
> 
> And have a great weekend btw!

Same to you !

2024-07-29 11:13 UTC, SeverusYixin commented
Hi@haesleinhuepf, me again :), when you have time, could you review if the code comments in this updated version are the type that you need!

2024-08-06 11:17 UTC, haesleinhuepf approved these changes
This looks very good @SeverusYixin , I'm going to merge it. Let's see what is the impace on the website.

2024-08-06 11:17 UTC, merged

2024-08-06 11:42 UTC, SeverusYixin commented
I'm happy to hear that :)