appssubmitter finial version
NFDI4BIOIMAGE/training pull request #128
Opened 2024-07-19 09:50 UTC by SeverusYixin

This webapp program contains a form (urls, author, description, license etc) and once the user clicks "submit", all things can be easily uploaded to github.

 To protect the security, the Github API key must be updated every 30 days.

This PR closes #94

2024-07-19 10:04 UTC, haesleinhuepf requested changes
Hi @SeverusYixin ,

awesome, thanks for sending this! Next time, it would be great if you could write a sentence, what this PR is about. Furthermore, I modified the sentence "closes #94" to your message. This will later close the corresponding issue, once this is merged.

May I also ask you for adding some documentation to our jupyter book? It would be great to have short user guide for your app with some screenshots. See [this page](https://nfdi4bioimage.github.io/training/contributing/index.html#step-by-step-tutorial) as example.

Thank you!

Best,
Robert

2024-07-19 14:26 UTC, SeverusYixin commented
> Hi @SeverusYixin ,
> 
> awesome, thanks for sending this! Next time, it would be great if you could write a sentence, what this PR is about. Furthermore, I modified the sentence "closes #94" to your message. This will later close the corresponding issue, once this is merged.
> 
> May I also ask you for adding some documentation to our jupyter book? It would be great to have short user guide for your app with some screenshots. See [this page](https://nfdi4bioimage.github.io/training/contributing/index.html#step-by-step-tutorial) as example.
> 
> Thank you!
> 
> Best, Robert

Ofc no problem, but which kinds of the documentation did you want me to add to our jupyter book? And I have a screeunshot of the APP, where should I upload it?
![appsubmitter](https://github.com/user-attachments/assets/4ae8e8ad-e751-4c5e-8a5f-625e9d7a64bc)

2024-07-19 14:35 UTC, haesleinhuepf commented
> where should I upload it?

As a new page next to [this one](https://github.com/NFDI4BIOIMAGE/training/blob/c4359fa7709f72d436cc44a9203255f23f0feb97/docs/_toc.yml#L9), certainly in the same [folder](https://github.com/NFDI4BIOIMAGE/training/tree/main/docs/contributing).

2024-07-23 08:13 UTC, haesleinhuepf commented
Hey @SeverusYixin ,

ok, this is super super cool!! 

May I ask for some minor modifications:
* Remove the submitter name
* Users should select the license from a list (e.g. the SPDX list)
* Users should select the tags from a list (they can select multiple), and there should be an option to add new tags
* Users should select the type from a list

2024-07-23 13:20 UTC, SeverusYixin commented
Hi @haesleinhuepf, if you can show me the current exact license list, tags list and type list it would be so helpful. Or can I just use the things that show up on the left side of https://nfdi4bioimage.github.io/training/readme.html directly?

2024-07-23 14:31 UTC, haesleinhuepf commented
@SeverusYixin 

For the license list, let's use the SPDX list you were using in #127 (so we don't reinvent the wheel here) : https://github.com/NFDI4BIOIMAGE/training/blob/f0aa3516ad0505219d3f461df75c5f3f95126f0c/scripts/data_normalizer.py#L7

The current lists of tags and content types can be retrieve as shown in #130 :
https://github.com/NFDI4BIOIMAGE/training/blob/7045d4888217d6b73c53080ba42d020475dd41fd/scripts/tag_statistics.ipynb

Let me know if you need anything else!

2024-07-23 14:47 UTC, SeverusYixin commented
> @SeverusYixin
> 
> For the license list, let's use the SPDX list you were using in #127 (so we don't reinvent the wheel here) :
> 
> https://github.com/NFDI4BIOIMAGE/training/blob/f0aa3516ad0505219d3f461df75c5f3f95126f0c/scripts/data_normalizer.py#L7
> 
> The current lists of tags and content types can be retrieve as shown in #130 : https://github.com/NFDI4BIOIMAGE/training/blob/7045d4888217d6b73c53080ba42d020475dd41fd/scripts/tag_statistics.ipynb
> 
> Let me know if you need anything else!

hmmm, that means I need retrieve the license by myself, am I right? 

And for https://github.com/NFDI4BIOIMAGE/training/blob/7045d4888217d6b73c53080ba42d020475dd41fd/scripts/tag_statistics.ipynb, it looks like only have the tags list, am I right?

2024-07-23 19:19 UTC, haesleinhuepf commented
> hmmm, that means I need retrieve the license by myself, am I right?

Yes

> it looks like only have the tags list, am I right?

Yes!

2024-07-24 16:13 UTC, SeverusYixin commented
Hi @haesleinhuepf, I have a question about URL,Description,Name,Authors. if the users add nothing to these, should they still be allowed to upload, or if they didn't enter the authors, should the submit be denied? For License, Tags and Type, the user chooses at least one, and I add an unknown choice for them. The yaml file also needs to be selected as it can be submitted.

2024-07-26 14:32 UTC, SeverusYixin commented
Hi @haesleinhuepf, me again :) Could you review this when you have a moment? And enjoy your holiday ：）

2024-08-06 11:52 UTC, haesleinhuepf requested changes
Hi @SeverusYixin ,

ok cool, the app looks great! I just tried it and have some minor requests:
* [x] It would be great if we could add tags which are not in the list of available tags: 
![image](https://github.com/user-attachments/assets/ad86a8d7-0150-47e5-9d54-eadb4150729e)

* [ ] make sure the changes are made on the most recent files. I just submitted a PR using the app (it worked 🥳 ) but it suggests many changes. I could imagine that this happens if my local repository is not up-to-date. [Details](https://github.com/NFDI4BIOIMAGE/training/pull/133/files). But we can pull the most recent file from github, before modifying the file e.g. using [this code](https://github.com/haesleinhuepf/git-bob/blob/83c7036f48ebe2a4363b09130498d46ffb5d0668/src/git_bob/_github_utilities.py#L396). 
* [ ] And below some suggestions in the code.

Otherwise, it's looking great!

Best,
Robert

2024-08-06 11:52 UTC, haesleinhuepf commented on scripts/appsubmitter.py
> +3. Submit the form to create a pull request.
```suggestion
Steps:
1. Select the YAML file for the type of training material.
2. Provide the necessary information.
3. Submit the form to create a pull request.
```
I suggest to remove this. It feels like a duplication of the sentence above and form entries below.

2024-08-06 11:52 UTC, haesleinhuepf commented on scripts/appsubmitter.py
> +    "Public-domain"
Could we use the fetch_spdx_function from here?
https://github.com/NFDI4BIOIMAGE/training/blob/d9146a54659482344e510c92df4e62beee0ad69e/scripts/data_normalizer.py#L9

2024-08-06 11:52 UTC, haesleinhuepf commented on scripts/appsubmitter.py
> +])
Could we determine this list dynamically from the yml files? E.g. as shown in the notebook here:

https://github.com/NFDI4BIOIMAGE/training/blob/7045d4888217d6b73c53080ba42d020475dd41fd/scripts/tag_statistics.ipynb

2024-08-06 11:52 UTC, haesleinhuepf commented on scripts/appsubmitter.py
> +    "Publication", "Publiction", "Python", "Slide", "Slides", "Tutorial", "Video", "Videos", "Workshop"
Same here. This list should be determined dynamically from the yml files.

2024-08-06 11:52 UTC, haesleinhuepf commented on scripts/appsubmitter.py
> +    'blog_posts.yml', 'events.yml', 'materials.yml', 'nfdi4bioimage.yml', 'papers.yml', 'workflow-tools.yml', 'youtube_channels.yml'
Could we determine this list using os.listdir?

2024-08-19 11:37 UTC, SeverusYixin commented
Hi @haesleinhuepf , me again :). If you have a moment, you can run this code for me to see if it works. Especially if the yml files are merged, does it still work on your side, so far no problem on mine.

 Also:
"normalisation_mapping = {}" function, will be removed after I update data_normalizer.py.

One question:
Since we have merged all the yml files, do we still need the 'YAML file selecter'? I think we can export it directly to the specified folder or file.

2024-08-19 14:05 UTC, SeverusYixin commented
It seems I don't have permission to change the data source? Would you mind changing it for me?

2024-08-23 05:12 UTC, haesleinhuepf commented
I'm not sure what you mean with "data source". Please let me know what exactly should be changed. Consider using http-links to point at code pecisely...

2024-08-26 07:18 UTC, SeverusYixin commented
> I'm not sure what you mean with "data source". Please let me know what exactly should be changed. Consider using http-links to point at code pecisely...

I mean for this:
"This branch has conflicts that must be resolved
Use the [web editor](https://github.com/NFDI4BIOIMAGE/training/pull/128/conflicts) or the  to resolve conflicts.
Conflicting files
resources/nfdi4bioimage.yml".

It seems I'm not allowed to update it.

2024-08-26 12:22 UTC, haesleinhuepf commented
ok, done

2024-08-26 13:30 UTC, SeverusYixin commented
> ok, done

Thank you :)

2024-08-27 11:28 UTC, SeverusYixin commented
Hi @haesleinhuepf, I have already updated it with the docstring. Take your time and check it out.

2024-08-27 11:40 UTC, haesleinhuepf requested changes
Hi @SeverusYixin ,

thanks for working on this! It would be great if you could reduce code-duplication, before we merge this. Instead of repeating similar functionality, consider re-using functions. This will result in much shorter code, which is easier to maintain obviously.

Thanks!

Best,
Robert

2024-08-27 11:40 UTC, haesleinhuepf commented on docs/contributing/index_2.md
> +We reserve the right to remove and modify entries in this collection at any time.
This duplicated text from the page before. Please only document your AppSubmitter in this page.

2024-08-27 11:40 UTC, haesleinhuepf commented on scripts/appsubmitter.py
> +        return yaml.safe_load(file)
Why are you not using this function?
https://github.com/NFDI4BIOIMAGE/training/blob/e19da868ae642588657fa268dd21a05d0faf2365/scripts/generate_link_lists.py#L117

2024-08-27 11:40 UTC, haesleinhuepf commented on scripts/appsubmitter.py
> +def get_yaml_files(resources_dir):
Why are you not using this function?
https://github.com/NFDI4BIOIMAGE/training/blob/e19da868ae642588657fa268dd21a05d0faf2365/scripts/generate_link_lists.py#L97

It gives you a DataFrame with all contents, which you can filter for unique entries in specific columns: df["license"].unique()

2024-08-27 11:40 UTC, haesleinhuepf commented on scripts/appsubmitter.py
> +        st.stop()
Consider using this function instead:
https://github.com/NFDI4BIOIMAGE/training/blob/e19da868ae642588657fa268dd21a05d0faf2365/scripts/_github_utilities.py#L8

2024-08-27 11:40 UTC, haesleinhuepf commented on scripts/tags_type_licence_retrieve.py
> +def load_yaml(file_path):
As mentioned above, consider using pre-existing functions instead of duplicating code.

2024-08-27 11:40 UTC, haesleinhuepf commented on scripts/tags_type_licence_retrieve.py
> +    return types
As mentioned above, consider re-using pre-existing functions, e.g. for retrieving a dataframe and then determine unique items in columns.

2024-08-27 11:40 UTC, haesleinhuepf commented on scripts/tags_type_licence_retrieve.py
> +                all_types.update(extract_types(yaml_content))
As mentioned above, reuse code instead of implementing the same thing multiple times.

2024-08-27 11:40 UTC, haesleinhuepf commented on scripts/tags_type_licence_retrieve.py
> +    types_output_file = os.path.abspath(os.path.join(os.path.dirname(__file__), 'types.txt'))
These three text files, what do we need them for?

2024-08-27 13:11 UTC, SeverusYixin commented on scripts/tags_type_licence_retrieve.py
> +                all_types.update(extract_types(yaml_content))
ahhh, you can delete this script, or I delete it. We don't need it anymore, I mean the scripts tags_type_licence_retrieve.py, I have already integrated it into the appsubmitter

2024-08-27 13:25 UTC, SeverusYixin commented on scripts/appsubmitter.py
> +def get_yaml_files(resources_dir):
Done!

2024-08-27 14:01 UTC, SeverusYixin commented on scripts/appsubmitter.py
> +        return yaml.safe_load(file)
Done

2024-08-27 18:27 UTC, haesleinhuepf commented on scripts/tags_type_licence_retrieve.py
> +                all_types.update(extract_types(yaml_content))
Please delete it. It's your branch.

2024-08-27 18:30 UTC, haesleinhuepf commented on scripts/appsubmitter.py
> +        st.stop()
I do not see your changes here until you commit and push them

2024-08-28 08:20 UTC, SeverusYixin commented on scripts/appsubmitter.py
> +        st.stop()
I'll push it after I'm done: "It gives you a DataFrame with all content, which you can filter for unique entries in specific columns: df["license"].unique()"

2024-08-28 09:02 UTC, SeverusYixin commented on scripts/appsubmitter.py
> +        st.stop()
> I do not see your changes here until you commit and push them

I marked it to told myself this is finished XD

2024-09-04 11:29 UTC, SeverusYixin commented
This PR also close #193

2024-09-06 07:56 UTC, SeverusYixin commented
Hi@haesleinhuepf, you can check it here, I have finished it

2024-09-09 12:37 UTC, haesleinhuepf reviewed
Hey @SeverusYixin ,

thanks for working on this! I left some comments below. Note: I will do these final modifications before merging this.

Thanks again!

2024-09-09 12:37 UTC, haesleinhuepf commented on docs/_toc.yml
> +    - file: contributing/index_2
I'm going to rename this file. "index_2" is not meaningful.

2024-09-09 12:37 UTC, haesleinhuepf commented on scripts/generate_link_lists.py
> +            new_content = read_yaml_file(os.path.join(directory_path, filename))  # Corrected line
Why is there a comment "# Corrected line" ?

2024-09-09 12:37 UTC, haesleinhuepf commented on scripts/appsubmitter.py
> +    return {'resources': resources}
This function is not used. I will remove it.

2024-09-09 12:37 UTC, haesleinhuepf commented on scripts/appsubmitter.py
> +directory_path = os.path.join('..', 'resources')
This will only work if you call the script from within the path "scripts/". You can determine the path, where appsubmitter.py is located using `__file__`. I will implement this for you.

2024-09-09 12:49 UTC, merged

2024-09-09 13:36 UTC, SeverusYixin commented on scripts/generate_link_lists.py
> +            new_content = read_yaml_file(os.path.join(directory_path, filename))  # Corrected line
That time, I tried this code to solve the problem, and write a comment to tell you. With this update, it will work again.

2024-09-09 14:51 UTC, haesleinhuepf commented on scripts/generate_link_lists.py
> +            new_content = read_yaml_file(os.path.join(directory_path, filename))  # Corrected line
Please to spread such comments in the code, they will accumulate over time and it will be hard to read. Consider using permalinks instead, like this one:

`https://github.com/NFDI4BIOIMAGE/training/blob/04cd328841d9b251e7eaf79f3b3b78ff94329687/scripts/generate_link_lists.py#L92`

Views like this:

https://github.com/NFDI4BIOIMAGE/training/blob/04cd328841d9b251e7eaf79f3b3b78ff94329687/scripts/generate_link_lists.py#L92

And is made by clicking here:

![image](https://github.com/user-attachments/assets/c0855c67-a80d-41e0-b305-1a4b84716a29)

2024-09-09 15:49 UTC, SeverusYixin commented on scripts/generate_link_lists.py
> +            new_content = read_yaml_file(os.path.join(directory_path, filename))  # Corrected line
Ok, I will create a branch to delete this comment