1st_version of the github_auto_add
NFDI4BIOIMAGE/training pull request #235
Opened 2024-10-10 14:00 UTC by SeverusYixin

Hi @haesleinhuepf, would you mind helping me review it?

closes #185
closes #246

2024-10-10 14:08 UTC, haesleinhuepf commented on scripts/auto-add-github-resources.py
> +    python auto_add_github_entry.py "username/repo" 123
```suggestion
    python auto_add_github_entry.py username/repo 123
```
I presume this is correct?

2024-10-10 14:13 UTC, SeverusYixin commented
Why can I not write this link like you did "https://github.com/NFDI4BIOIMAGE/training/blob/2f17431f8fbd1ee4ffb205eb6fe26474a04ec41a/scripts/auto-add-zenodo-entry.py#L1"?

2024-10-10 14:13 UTC, haesleinhuepf requested changes
Hi @SeverusYixin ,

awesome, thanks for this! Two things: 
1. Before sending a PR, please check if the tool works as you describe it in the documentation.
2. I just tested it and received an error message. That's the command I ran:
```
python scripts/auto-add-github-resources.py nfdi4bioimage/training 236
```

And that's the error:
```
-> get_conversation_on_issue(nfdi4bioimage/training, 236)
Request GET /repos/rmassei/ymia_python_event_series_material/collaborators?per_page=1 failed with 403: Forbidden
Traceback (most recent call last):
  File "C:\structure\code\training\scripts\auto-add-github-resources.py", line 139, in <module>
    main()
  File "C:\structure\code\training\scripts\auto-add-github-resources.py", line 34, in main
    github_data_dict = complete_github_data(github_repo_url)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\structure\code\training\scripts\auto-add-github-resources.py", line 97, in complete_github_data
    if collaborators.totalCount > 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\PaginatedList.py", line 192, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\Requester.py", line 550, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\Requester.py", line 715, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\Requester.py", line 812, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\Requester.py", line 846, in __requestRaw
    response = cnx.getresponse()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\Requester.py", line 198, in getresponse
    r = verb(
        ^^^^^
  File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\urllib3\connectionpool.py", line 934, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\GithubRetry.py", line 187, in increment
    raise Requester.createException(response.status, response.headers, content)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
github.GithubException.GithubException: 403 {"message": "Must have push access to view repository collaborators.", "documentation_url": "https://docs.github.com/rest/collaborators/collaborators#list-repository-collaborators", "status": "403"}
```

Let me know if I should try again!

And thanks again for working on this. This will be cool to have!

Best,
Robert

2024-10-10 14:15 UTC, SeverusYixin commented on scripts/auto-add-github-resources.py
> +    python auto_add_github_entry.py "username/repo" 123
I have deleted it. I wanted to test it locally or on my github, but it seems I'm not allowed to.

2024-10-10 14:18 UTC, SeverusYixin commented
> Hi @SeverusYixin ,
> 
> awesome, thanks for this! Two things:
> 
> 1. Before sending a PR, please check if the tool works as you describe it in the documentation.
> 2. I just tested it and received an error message. That's the command I ran:
> 
> ```
> python scripts/auto-add-github-resources.py nfdi4bioimage/training 236
> ```
> 
> And that's the error:
> 
> ```
> -> get_conversation_on_issue(nfdi4bioimage/training, 236)
> Request GET /repos/rmassei/ymia_python_event_series_material/collaborators?per_page=1 failed with 403: Forbidden
> Traceback (most recent call last):
>   File "C:\structure\code\training\scripts\auto-add-github-resources.py", line 139, in <module>
>     main()
>   File "C:\structure\code\training\scripts\auto-add-github-resources.py", line 34, in main
>     github_data_dict = complete_github_data(github_repo_url)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\structure\code\training\scripts\auto-add-github-resources.py", line 97, in complete_github_data
>     if collaborators.totalCount > 0:
>        ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\PaginatedList.py", line 192, in totalCount
>     headers, data = self.__requester.requestJsonAndCheck(
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\Requester.py", line 550, in requestJsonAndCheck
>     return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\Requester.py", line 715, in requestJson
>     return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\Requester.py", line 812, in __requestEncode
>     status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
>                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\Requester.py", line 846, in __requestRaw
>     response = cnx.getresponse()
>                ^^^^^^^^^^^^^^^^^
>   File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\Requester.py", line 198, in getresponse
>     r = verb(
>         ^^^^^
>   File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\requests\sessions.py", line 602, in get
>     return self.request("GET", url, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\requests\sessions.py", line 589, in request
>     resp = self.send(prep, **send_kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\requests\sessions.py", line 703, in send
>     r = adapter.send(request, **kwargs)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\requests\adapters.py", line 667, in send
>     resp = conn.urlopen(
>            ^^^^^^^^^^^^^
>   File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\urllib3\connectionpool.py", line 934, in urlopen
>     retries = retries.increment(method, url, response=response, _pool=self)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\rober\miniforge3\envs\devbio-napari-env\Lib\site-packages\github\GithubRetry.py", line 187, in increment
>     raise Requester.createException(response.status, response.headers, content)  # type: ignore
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> github.GithubException.GithubException: 403 {"message": "Must have push access to view repository collaborators.", "documentation_url": "https://docs.github.com/rest/collaborators/collaborators#list-repository-collaborators", "status": "403"}
> ```
> 
> Let me know if I should try again!
> 
> And thanks again for working on this. This will be cool to have!
> 
> Best, Robert

The problem is that I can not test it, it told me the scads.ai clould refuse me XD

2024-10-10 15:02 UTC, haesleinhuepf commented
What is "scads.ai clould" in this context? What was the exact error message?

2024-10-10 20:11 UTC, haesleinhuepf commented
The error above is not about our repository:
> Request GET /repos/rmassei/ymia_python_event_series_material/collaborators?per_page=1 failed with 403: Forbidden
> ...
> Must have push access to view repository collaborators.

The error happens when accessing the other repository. I'd say we will not be able to read out collaborators from remote repositories.

2024-10-11 07:21 UTC, SeverusYixin commented
> The error above is not about our repository:
> 
> > Request GET /repos/rmassei/ymia_python_event_series_material/collaborators?per_page=1 failed with 403: Forbidden
> > ...
> > Must have push access to view repository collaborators.
> 
> The error happens when accessing the other repository. I'd say we will not be able to read out collaborators from remote repositories.

Yes, I used the code snippet to check locally that the link to our repository is no problem, it show me as PS C:\Users\huang\Documents\GitHub\training\scripts> & 'c:\Users\huang\AppData\Local\Programs\ Python\Python312\python. exe' 'c:\Users\huang\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\adapter/ ... /... \debugpy\launcher' "51870" "--" "C:\Users\huang\Documents\GitHub\training\scripts\test.py"
Token found: githu
Repository successfully accessed: NFDI4BIOIMAGE/training
PS C:\Users\huang\Documents\GitHub\training\scripts> 

I'm trying to see if this can be avoided, but nothing I've seen so far seems to work! Or maybe not with github token, I'm not sure

2024-10-11 07:22 UTC, haesleinhuepf commented
> nothing I've seen so far seems to work!

Yes, it is possible that this will not work. Do you have an overview about which meta data we can access and which not?

2024-10-11 08:02 UTC, SeverusYixin commented
> > nothing I've seen so far seems to work!
> 
> Yes, it is possible that this will not work. Do you have an overview about which meta data we can access and which not?

At the moment, it looks like the request will be denied when you try to access it with github token.

2024-10-11 08:07 UTC, haesleinhuepf commented
Can you please try "repo.get_contributors()" instead of "repo.get_collaborators()"?

2024-10-11 08:08 UTC, SeverusYixin commented
> Can you please try "repo.get_contributors()" instead of "repo.get_collaborators()"?

Let me try

2024-10-11 09:00 UTC, haesleinhuepf commented
Did it work?

2024-10-11 09:13 UTC, SeverusYixin commented
> Did it work?

no

2024-10-11 09:36 UTC, SeverusYixin commented
Please do not merge. There are still some details to discuss :)

1. Currently it looks like #238, so again, what should the name be, "ymia_python_event_series_material" or "YMIA - Python-Based Event Series Training Material"?

2. and for tags, do we need this "tags: No tags available"? or this "tags:   "

2024-10-11 09:46 UTC, haesleinhuepf commented
> 1. "ymia_python_event_series_material" or "YMIA - Python-Based Event Series Training Material"?

I would use whatever the github returns as `repo.name`

> 2\. and for tags, do we need this "tags: No tags available"? or this "tags:   "

If there are no tags, we should not have  a "tag:" in our yaml.

2024-10-11 09:47 UTC, haesleinhuepf commented
> no

Consider posting an error message, in case you wish that I assist you.

2024-10-11 09:57 UTC, SeverusYixin commented
> Consider posting an error message, in case you wish that I assist you.

Already solved, thank you if I need that I will post a error message. Thank you again :)

2024-10-21 15:07 UTC, haesleinhuepf commented
Are there any news here @SeverusYixin ? Shall I test it agian?

2024-10-21 17:19 UTC, SeverusYixin commented
> Are there any news here @SeverusYixin ? Shall I test it agian?

Seems like you didn't see issues #185.

I asked you how should we define the type and tag for a github repositorie. Except for type and day, all other functions are implemented.

2024-10-22 08:15 UTC, SeverusYixin commented
write something for the tags like "Dear users, please add a tags"

2024-10-22 08:17 UTC, SeverusYixin commented
And never have empty strings

2024-10-22 09:25 UTC, SeverusYixin commented
Hi @haesleinhuepf, please review again, if everything is ok then we can close and merge this.

Thank you :)

2024-10-28 13:26 UTC, haesleinhuepf commented on scripts/auto-add-github-resources.py
> +        entry['license'] = ""
```suggestion
        pass
```

2024-10-28 13:26 UTC, haesleinhuepf commented on scripts/auto-add-github-resources.py
> +        entry['license'] = license_info.license.name if license_info else ""
```suggestion
        if license_info is not None:
            entry['license'] = license_info.license.name
```

2024-10-28 13:27 UTC, haesleinhuepf commented on scripts/auto-add-github-resources.py
> +    entry['name'] = repo.name if repo.name else ""
```suggestion
    entry['name'] = repo.name
```

2024-10-28 13:30 UTC, haesleinhuepf commented on scripts/auto-add-github-resources.py
> +        return repo.created_at.isoformat() if repo.created_at else ""
```suggestion
    elif repo.created_at is not None:
        return repo.created_at.isoformat()
```

2024-10-28 13:32 UTC, haesleinhuepf commented on scripts/auto-add-github-resources.py
> +    """
```suggestion
    entry['tags'] = "TODO"
```

2024-10-28 13:32 UTC, haesleinhuepf commented on scripts/auto-add-github-resources.py
> +    res = send_pull_request(repository, branch, "Add " + github_repo_url, f"closes #{issue}")
```suggestion
    res = send_pull_request(repository, branch, "Add " + github_repo_url, f"""This is an automatically created pull-request. Before merging this, please make sure
* [ ] has proper `tags` set.
* [ ] has reasonable content `type` depending on the content of the github repository.
 [Read more](https://nfdi4bioimage.github.io/training/contributing/format.html) 
   
closes #{issue}
""")
```

2024-10-31 08:43 UTC, merged