Upgrade all versions base on V4
NFDI4BIOIMAGE/training pull request #294
Opened 2024-10-18 08:18 UTC by SeverusYixin

2024-10-21 15:05 UTC, haesleinhuepf requested changes
Please remove the comments from your modifications. I do not understand, why they are necessary. Also in the future, please avoid those.

2024-10-21 15:05 UTC, haesleinhuepf commented on .github/workflows/auto-add-download-statistics.yml
> +      uses: actions/setup-python@v4  # Updated to the latest version of the action
Why is this comment necessary??

2024-10-22 07:49 UTC, SeverusYixin commented
Hi @haesleinhuepf, you can review it again and then close it.

2024-10-22 07:51 UTC, haesleinhuepf commented
Awesome, thanks!

2024-10-22 07:51 UTC, merged

2024-10-22 07:53 UTC, SeverusYixin commented
You are welcome!