Update: add page organized by date
NFDI4BIOIMAGE/training pull request #326
Opened 2024-10-25 09:52 UTC by SeverusYixin

This PR relate to #117 NFDI4BIOIMAGE/nfdi_search_engine#27
This PR closes #117 NFDI4BIOIMAGE/nfdi_search_engine#27

2024-10-25 12:43 UTC, SeverusYixin commented
Hello @haesleinhuepf, it's me again! Could you take a moment to review this?

I noticed something interesting: your original _toc.yml worked perfectly, but after my update, I had to adjust its position to make it work. Do you have any idea why that might be?

2024-10-25 13:27 UTC, haesleinhuepf reviewed
Looks good @SeverusYixin ! Just two minor questions. In general: try to change only things that are relevant for your work and leave the rest untouched

2024-10-25 13:27 UTC, haesleinhuepf commented on docs/_toc.yml
> -    # when adding new chapters here, don't forget to also add them to the scipts/generate_link_lists.py file
Why are you removing this?

2024-10-25 13:27 UTC, haesleinhuepf commented on docs/_toc.yml
> +      - file: statistics/readme
Why are you adding spaces here?

2024-10-25 13:37 UTC, SeverusYixin commented on docs/_toc.yml
> -    # when adding new chapters here, don't forget to also add them to the scipts/generate_link_lists.py file
I mistakenly deleted it when I was editing the script, but I then restored it, but it wasn't updated

2024-10-25 13:39 UTC, SeverusYixin commented on docs/_toc.yml
> +      - file: statistics/readme
Because without space, the checks cannot be passed, just like other space

2024-10-25 13:52 UTC, SeverusYixin commented on docs/_toc.yml
> +      - file: statistics/readme
At first, I used your original script and just add "  - caption: What's New
    chapters:
{date_toc}
", but the check can not be passed as the https://github.com/NFDI4BIOIMAGE/training/pull/326/commits/78059c5ccf362a3fefbf1cec29a43c99912f9048. That's why  I asked you as "https://github.com/NFDI4BIOIMAGE/training/pull/326#issuecomment-2437680716"

2024-10-30 11:05 UTC, haesleinhuepf commented on scripts/generate_link_lists.py
> +    # Generate the 'What's New' page with content sorted by publish date
```suggestion
    # Generate the 'What's New' page with content sorted by publication date
```

2024-10-30 11:06 UTC, haesleinhuepf commented on scripts/generate_link_lists.py
> +    generate_by_publish_date(content, "docs/whats_new.md")
```suggestion
    generate_by_publication_date(content, "docs/whats_new.md")  
```

2024-10-30 11:06 UTC, haesleinhuepf commented on scripts/generate_link_lists.py
> +def generate_by_publish_date(content, output_file):
```suggestion
def generate_by_publication_date(content, output_file):
```

2024-10-31 08:53 UTC, haesleinhuepf requested changes
Hi @SeverusYixin ,

that looks already quite good. I just tested it by building the page and must note that the links do not look nice:

![image](https://github.com/user-attachments/assets/3a6266b7-a936-48dd-86a3-abb3464e7d0b)

I think it would be better if the two links are on two lines and the [Link to content] stuff should dissapper. After modifying the code, consider trying it out and have a look at the page. All you need to execute locally are [these lines](https://github.com/NFDI4BIOIMAGE/training/blob/main/.github/workflows/book.yml#L35-L37).  

Thanks!

Best,
Robert

2024-10-31 08:55 UTC, haesleinhuepf commented
Also a hint: If you want this pull-request to close multiple issues, you must write "closes #" multiple times. You can see which issues are closed by hovering with your mouse overt the word "closes":

![image](https://github.com/user-attachments/assets/0b91ad4a-823b-4a6c-bd9a-0d97d88f0d81)

2024-11-01 09:54 UTC, SeverusYixin commented
> Also a hint: If you want this pull-request to close multiple issues, you must write "closes #" multiple times. You can see which issues are closed by hovering with your mouse overt the word "closes":
> 
> ![image](https://private-user-images.githubusercontent.com/12660498/381887008-0b91ad4a-823b-4a6c-bd9a-0d97d88f0d81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTUxNDEsIm5iZiI6MTczMDQ1NDg0MSwicGF0aCI6Ii8xMjY2MDQ5OC8zODE4ODcwMDgtMGI5MWFkNGEtODIzYi00YTZjLWJkOWEtMGQ5N2Q4OGYwZDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA5NTQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NGMwNTNkYWI1YjZkYTZhMTVlYmFmYTRjMmU1ZTEwZGRjMTUxNzViMGQ0NjEyZTI3Yzg5N2M2OWE2OGExY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AUuMeTARS1vh_tzg0CzRvX-O7D5_pUAgqYmvUELkkvg)

Thank you

2024-11-01 09:57 UTC, SeverusYixin commented
> Hi @SeverusYixin ,
> 
> that looks already quite good. I just tested it by building the page and must note that the links do not look nice:
> 
> ![image](https://private-user-images.githubusercontent.com/12660498/381885855-3a6266b7-a936-48dd-86a3-abb3464e7d0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTUxNDIsIm5iZiI6MTczMDQ1NDg0MiwicGF0aCI6Ii8xMjY2MDQ5OC8zODE4ODU4NTUtM2E2MjY2YjctYTkzNi00OGRkLTg2YTMtYWJiMzQ2NGU3ZDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA5NTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZWEwMDZjYzNmNTlmYWMyOGY4YTMxNDU2M2NkYzAzYzk1NTFiNTIwODNiOTk2ODE3MDNhYmY1MzYzNGVhNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jQkpjC4cHYWXDYdD1XfDOkEZ_AsPZX2F4k3CpFnNbi8)
> 
> I think it would be better if the two links are on two lines and the [Link to content] stuff should dissapper. After modifying the code, consider trying it out and have a look at the page. All you need to execute locally are [these lines](https://github.com/NFDI4BIOIMAGE/training/blob/main/.github/workflows/book.yml#L35-L37).
> 
> Thanks!
> 
> Best, Robert

Hi @haesleinhuepf, would you like to merge this PR first, and then create a new issue assigned to me for the Outlook styling improvements?

2024-11-01 11:07 UTC, haesleinhuepf commented
I prefer fixing bugs in new pages before they become part of the public website. Thanks!

2024-11-06 11:20 UTC, haesleinhuepf commented
Hi @SeverusYixin,

I was just wondering why the lists on this page look different than the lists on other pages? Do you think it would be possible to reuse [code building the pages](https://github.com/NFDI4BIOIMAGE/training/blob/2d2e9e85c541ba4167b798f990f43b9ca9ef85fd/scripts/generate_link_lists.py#L382) also to avoid the bug discussed above?

Thanks!
Robert

2024-11-06 11:40 UTC, SeverusYixin commented
> Hi @SeverusYixin,
> 
> I was just wondering why the lists on this page look different than the lists on other pages? Do you think it would be possible to reuse [code building the pages](https://github.com/NFDI4BIOIMAGE/training/blob/2d2e9e85c541ba4167b798f990f43b9ca9ef85fd/scripts/generate_link_lists.py#L382) also to avoid the bug discussed above?
> 
> Thanks! Robert

Let me try it later and give you an answer

2024-11-07 15:49 UTC, SeverusYixin reviewed
This is my PR, and I cannot be a reviewer to approve your changes.

2024-11-07 15:57 UTC, merged